version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      # - "3000:80"
      - "443:443"
    tty: true
    restart: always
  
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend-vol:/usr/src/app/data
      - ../mm_docs:/usr/src/app/mm_docs
    tty: true
    restart: always

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ../qdrant_data:/qdrant/storage
    restart: always